basePath: /
definitions:
  dto.CompanyRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: CTD Backend API
  title: Predict Ticket Department API
  version: "1.0"
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Authenticate and get JWT token
      parameters:
      - description: Company credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CompanyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login company
      tags:
      - Company
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Create new company accout
      parameters:
      - description: Company credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CompanyRequest'
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register company
      tags:
      - Company
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
